In [1]:
import csv
import pandas as pd
import numpy as np
import logging
import os

In [2]:
# Set up logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler("data_loading.log"),
        logging.StreamHandler()
    ]
)

In [3]:
# Read MIMICs CSV files
subfolder = 'o3_hour_overlap_window'

# Log the start of the process
logging.info(f"Starting the data loading process from {subfolder}...")

logging.info(f"Loading MIMIC-IV datasets")
try:
    mimic_mean_df = pd.read_csv(f"../01_MimicIV/CSV/Exports/datasets/whole_set/{subfolder}/o01_final_mean_with_los.csv", low_memory=False)
    logging.info("Loaded mimic_mean_df successfully.")
except Exception as e:
    logging.error(f"Error loading mimic_mean_df: {e}")

try:
    mimic_median_df = pd.read_csv(f"../01_MimicIV/CSV/Exports/datasets/whole_set/{subfolder}/o02_final_median_with_los.csv", low_memory=False)
    logging.info("Loaded mimic_median_df successfully.")
except Exception as e:
    logging.error(f"Error loading mimic_median_df: {e}")

try:
    mimic_min_df = pd.read_csv(f"../01_MimicIV/CSV/Exports/datasets/whole_set/{subfolder}/o03_final_min_with_los.csv", low_memory=False)
    logging.info("Loaded mimic_min_df successfully.")
except Exception as e:
    logging.error(f"Error loading mimic_min_df: {e}")

try:
    mimic_max_df = pd.read_csv(f"../01_MimicIV/CSV/Exports/datasets/whole_set/{subfolder}/o04_final_max_with_los.csv", low_memory=False)
    logging.info("Loaded mimic_max_df successfully.")
except Exception as e:
    logging.error(f"Error loading mimic_max_df: {e}")

# Read eICUs CSV files
logging.info("Loading eICU datasets")
try:
    eicu_mean_df = pd.read_csv(f"../02_eICU/CSV/Exports/datasets/whole_set/{subfolder}/o01_final_mean_table.csv", low_memory=False)
    logging.info("Loaded eicu_mean_df successfully.")
except Exception as e:
    logging.error(f"Error loading eicu_mean_df: {e}")

try:
    eicu_median_df = pd.read_csv(f"../02_eICU/CSV/Exports/datasets/whole_set/{subfolder}/o02_final_median_table.csv", low_memory=False)
    logging.info("Loaded eicu_median_df successfully.")
except Exception as e:
    logging.error(f"Error loading eicu_median_df: {e}")

try:
    eicu_min_df = pd.read_csv(f"../02_eICU/CSV/Exports/datasets/whole_set/{subfolder}/o03_final_min_table.csv", low_memory=False)
    logging.info("Loaded eicu_min_df successfully.")
except Exception as e:
    logging.error(f"Error loading eicu_min_df: {e}")

try:
    eicu_max_df = pd.read_csv(f"../02_eICU/CSV/Exports/datasets/whole_set/{subfolder}/o04_final_max_table.csv", low_memory=False)
    logging.info("Loaded eicu_max_df successfully.")
except Exception as e:
    logging.error(f"Error loading eicu_max_df: {e}")

logging.info("Data loading process completed.")

2025-03-22 22:45:19,777 - INFO - Starting the data loading process from o3_hour_overlap_window...
2025-03-22 22:45:19,780 - INFO - Loading MIMIC-IV datasets
2025-03-22 22:45:26,749 - INFO - Loaded mimic_mean_df successfully.
2025-03-22 22:45:33,528 - INFO - Loaded mimic_median_df successfully.
2025-03-22 22:45:39,862 - INFO - Loaded mimic_min_df successfully.
2025-03-22 22:45:46,661 - INFO - Loaded mimic_max_df successfully.
2025-03-22 22:45:46,662 - INFO - Loading eICU datasets
2025-03-22 22:45:49,153 - INFO - Loaded eicu_mean_df successfully.
2025-03-22 22:45:51,433 - INFO - Loaded eicu_median_df successfully.
2025-03-22 22:45:53,600 - INFO - Loaded eicu_min_df successfully.
2025-03-22 22:45:55,657 - INFO - Loaded eicu_max_df successfully.
2025-03-22 22:45:55,658 - INFO - Data loading process completed.

In [4]:
display (mimic_mean_df)

,row_count,subject_id,hadm_id,Time_Zone,gender,age,language,marital_status,race,Base Excess - Mean,...,Other - Mean.2,"Triglycerides, Pleural - Mean",Thoracic Fluid Content (TFC) (NICOM) - Mean,Head of Bed Measurement (Degree) - Mean,ARCH-1 - Mean,Factor VII - Mean,"Creatinine, Body Fluid - Mean",Ethanol - Mean,hospital_expire_flag,los
0,1,10004733,27411876,1,M,51,English,SINGLE,UNKNOWN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Survive,8.357373
1,2,10004733,27411876,2,M,51,English,SINGLE,UNKNOWN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Survive,8.357373
2,3,10004733,27411876,3,M,51,English,SINGLE,UNKNOWN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Survive,8.357373
3,4,10004733,27411876,4,M,51,English,SINGLE,UNKNOWN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Survive,8.357373
4,5,10004733,27411876,5,M,51,English,SINGLE,UNKNOWN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Survive,8.357373
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58139,58140,19999987,23865745,12,F,57,English,NaN,UNKNOWN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Survive,1.937847
58140,58141,19999987,23865745,13,F,57,English,NaN,UNKNOWN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Survive,1.937847
58141,58142,19999987,23865745,14,F,57,English,NaN,UNKNOWN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Survive,1.937847
58142,58143,19999987,23865745,15,F,57,English,NaN,UNKNOWN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Survive,1.937847
58143,58144,19999987,23865745,16,F,57,English,NaN,UNKNOWN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Survive,1.937847